.base: &base
    user: cyklista
    port: 22
    identityFile: ~/.ssh/id_rsa
    forwardAgent: true
    multiplexing: true
    sshOptions:
        UserKnownHostsFile: /dev/null
        StrictHostKeyChecking: no
    roles:
        - app
        - db
    bin/php: php72
    http_user: cyklista

pt.cyklista.usermd.net:
    <<: *base
    hostname: pt.cyklista.usermd.net
    stage: prod
    deploy_path: /usr/home/cyklista/domains/pt.cyklista.usermd.net
    branch: master